// utils/keywordMatching.ts
import { normalizeText } from './normalizeText';
// Palabras clave para cada categoría
const keywords = {
    cotizar: [
        'cotizar',
        'cotizacion',
        'cotización',
        'presupuesto',
        'precio',
        'cuanto cuesta',
        'cuánto cuesta',
        'cuanto vale',
        'cuánto vale',
        'cuanto sale',
        'cuánto sale',
        'quiero cotizar',
        'necesito cotizar',
        'solicitar cotización',
        'pedir cotización',
        'pedir presupuesto',
        'necesito un presupuesto',
        'precio estimado',
        'precio aproximado',
        'valor del servicio',
        'cuál es el costo',
        'me gustaría saber el precio',
        'solicitar presupuesto',
        'precio total',
        'precio por unidad',
        'costo',
        'tarifa',
        'tarifario',
        'costo total',
        'inversión',
        'valor total',
        'valor estimado',
        'estimado de precio',
        'cotización aproximada',
        'presupuesto estimado',
        'solicitud de precio',
        'precio de lista',
        'precio sugerido',
        'rango de precios',
        'precio referencial',
        'cuánto sería',
        'cuánto debo pagar',
        'precio por cantidad',
        'precio especial',
        'me podrían cotizar',
        'solicitud de cotización',
        'precio de mercado',
        'quiero saber el costo',
        'cuál sería el precio',
        'me pueden pasar precio',
        'cuál es la tarifa',
        'tarifa aproximada',
        'necesito un precio',
        'quiero saber cuánto cuesta',
        'consulta de precios',
        'consulta de presupuesto',
        'consulta de cotización',
        '¿cuánto es?',
        'coste',
        'requerir cotización',
        'precio final',
        'solicito un presupuesto',
        'pedido de cotización',
        '¿me pasas un presupuesto?',
        'dame un estimado',
        'precio por servicio',
        'costo por producto',
        'valor aproximado',
        'precio completo',
        '¿qué cuesta?',
        '¿qué valor tiene?',
        'valor total del servicio',
      ],
      modificar: [
        'modificar',
        'cambiar',
        'editar',
        'ajustar',
        'actualizar',
        'corregir',
        'rectificar',
        'alterar',
        'quiero modificar',
        'necesito cambiar',
        'hacer modificaciones',
        'hacer cambios',
        'modificación',
        'modificaciones',
        'revisar',
        'reajustar',
        'adaptar',
        'reestructurar',
        'ajustar detalles',
        'ajustes',
        'revisar y cambiar',
        'mejorar',
        'hacer ajustes',
        'poner al día',
        'modificar detalles',
        'modificar parámetros',
        'afinar',
        'retocar',
        'reformar',
        'transformar',
        'reformular',
        'reconfigurar',
        'hacer correcciones',
        'refinar',
        'rectificación',
        'revisión',
        'reparar',
        'revisar información',
        'modificar archivo',
        'cambiar configuración',
        'modificar datos',
        'modificar contenido',
        'ajustar configuración',
        'reemplazar',
        'intercambiar',
        'sustituir',
        'hacer ediciones',
        'variar',
        'reajustar configuración',
        'revisar y ajustar',
        'personalizar',
        'adaptar cambios',
        'cambiar detalles',
        'modificar valores',
        'refrescar',
        'recargar',
        'modificar opciones',
        'recomponer',
        'mejorar configuración',
        'reorganizar',
        'modificar diseño',
        'reajustar detalles',
      ]
      ,
      confirmar: [
        'sí',
        'si',
        'claro',
        'por supuesto',
        'definitivamente',
        'exacto',
        'afirmativo',
        'seguro',
        'de acuerdo',
        'vale',
        'vale la pena',
        'totalmente',
        'por supuesto que sí',
        'sin duda',
      ],
      negar: [
        'no',
        'negativo',
        'de ninguna manera',
        'nunca',
        'en absoluto',
        'no gracias',
        'para nada',
        'no lo creo',
        'no estoy seguro',
        'no quiero',
        'no me interesa',
        'rechazo',
        'imposible',
        'definitivamente no',
        'de ninguna forma',
        'ni pensarlo',
        'lo descarto',
        'no es posible',
        'no lo veo posible',
        'no tengo interés',
        'lo niego',
        'ni de broma',
        'de ninguna',
        'ni hablar',
        'no va a pasar'
      ],
      duda: [
        'quizás',
        'tal vez',
        'no estoy seguro',
        'no sé',
        'puede ser',
        'no lo sé',
        'no tengo claro',
        'no lo tengo claro',
        'no estoy convencido',
        'me genera dudas',
        'no estoy del todo seguro',
        'tengo mis dudas',
        'no estoy completamente seguro',
        'no estoy seguro al 100%',
        'me hace dudar',
        'no me queda claro',
        'no lo tengo del todo claro',
        'tengo incertidumbre',
        'dudo sobre eso',
        'no estoy del todo convencido',
        'tengo ciertas dudas',
        'aún lo estoy pensando',
        'me lo estoy cuestionando',
        'no estoy seguro de eso',
        'no me convence del todo'
      ],
      reiniciar: [
        'reiniciar',
        'empezar de nuevo',
        'comenzar de nuevo',
        'volver a iniciar',
        'resetear',
        'volver al inicio',
        'comenzar otra vez',
        'empezar otra vez',
        'volver a empezar',
        'borrar y empezar de nuevo',
        'recomenzar',
        'iniciar desde cero',
        'arrancar de nuevo',
        'hacerlo desde el principio',
        'reiniciar conversación',
        'comenzar una nueva consulta',
        'abrir nueva cotización',
        'crear una nueva conversación',
        'resetear interacción',
        'empezar nueva solicitud',
        'abrir una nueva consulta',
        'comenzar nueva solicitud',
        'crear otra consulta',
        'volver a preguntar',
        'nueva cotización',
        'iniciar otra consulta'
      ],
  };
  
// Función que identifica la categoría de la entrada del usuario
export const getCategoryFromInput = (
  input: string
):  'cotizar' | 'modificar' | 'confirmar' | 'negar' | 'duda' | 'reiniciar' | 'desconocido' => {
  // Normalizar el texto primero
  const normalizedInput = normalizeText(input);

  // Buscar en cada categoría
  for (const [category, kws] of Object.entries(keywords)) {
    if (kws.some((keyword) => normalizedInput.includes(keyword))) {
      return category as 'cotizar' | 'modificar' |'confirmar' | 'negar' | 'duda' | 'reiniciar';
    }
  }

  return 'desconocido';
};
  