// utils/keywordMatching.ts

// Palabras clave para cada categoría
const keywords = {
    cotizar: [
        'cotizar',
        'cotizacion',
        'cotización',
        'presupuesto',
        'precio',
        'cuanto cuesta',
        'cuánto cuesta',
        'cuanto vale',
        'cuánto vale',
        'cuanto sale',
        'cuánto sale',
        'quiero cotizar',
        'necesito cotizar',
        'solicitar cotización',
        'pedir cotización',
        'pedir presupuesto',
        'necesito un presupuesto',
        'precio estimado',
        'precio aproximado',
        'valor del servicio',
        'cuál es el costo',
        'me gustaría saber el precio',
        'solicitar presupuesto',
        'precio total',
        'precio por unidad',
        'costo',
        'tarifa',
        'tarifario',
        'costo total',
        'inversión',
        'valor total',
        'valor estimado',
        'estimado de precio',
        'cotización aproximada',
        'presupuesto estimado',
        'solicitud de precio',
        'precio de lista',
        'precio sugerido',
        'rango de precios',
        'precio referencial',
        'cuánto sería',
        'cuánto debo pagar',
        'precio por cantidad',
        'precio especial',
        'me podrían cotizar',
        'solicitud de cotización',
        'precio de mercado',
        'quiero saber el costo',
        'cuál sería el precio',
        'me pueden pasar precio',
        'cuál es la tarifa',
        'tarifa aproximada',
        'necesito un precio',
        'quiero saber cuánto cuesta',
        'consulta de precios',
        'consulta de presupuesto',
        'consulta de cotización',
        '¿cuánto es?',
        'coste',
        'requerir cotización',
        'precio final',
        'solicito un presupuesto',
        'pedido de cotización',
        '¿me pasas un presupuesto?',
        'dame un estimado',
        'precio por servicio',
        'costo por producto',
        'valor aproximado',
        'precio completo',
        '¿qué cuesta?',
        '¿qué valor tiene?',
        'valor total del servicio',
      ],
      modificar: [
        'modificar',
        'cambiar',
        'editar',
        'ajustar',
        'actualizar',
        'corregir',
        'rectificar',
        'alterar',
        'quiero modificar',
        'necesito cambiar',
        'hacer modificaciones',
        'hacer cambios',
        'modificación',
        'modificaciones',
        'revisar',
        'reajustar',
        'adaptar',
        'reestructurar',
        'ajustar detalles',
        'ajustes',
        'revisar y cambiar',
        'mejorar',
        'hacer ajustes',
        'poner al día',
        'modificar detalles',
        'modificar parámetros',
        'afinar',
        'retocar',
        'reformar',
        'transformar',
        'reformular',
        'reconfigurar',
        'hacer correcciones',
        'refinar',
        'rectificación',
        'revisión',
        'reparar',
        'revisar información',
        'modificar archivo',
        'cambiar configuración',
        'modificar datos',
        'modificar contenido',
        'ajustar configuración',
        'reemplazar',
        'intercambiar',
        'sustituir',
        'hacer ediciones',
        'variar',
        'reajustar configuración',
        'revisar y ajustar',
        'personalizar',
        'adaptar cambios',
        'cambiar detalles',
        'modificar valores',
        'refrescar',
        'recargar',
        'modificar opciones',
        'recomponer',
        'mejorar configuración',
        'reorganizar',
        'modificar diseño',
        'reajustar detalles',
      ]
      ,
  };
  
  // Función que identifica si la entrada del usuario pertenece a una categoría
  export const getCategoryFromInput = (
    input: string
  ): 'cotizar' | 'modificar' | 'desconocido' => {
    // Busca si el input contiene alguna palabra clave de cotización
    if (keywords.cotizar.some((keyword) => input.includes(keyword))) {
      return 'cotizar';
    }
  
    // Busca si el input contiene alguna palabra clave de modificación
    if (keywords.modificar.some((keyword) => input.includes(keyword))) {
      return 'modificar';
    }
  
    // Si no encuentra coincidencias, devolver 'desconocido'
    return 'desconocido';
  };
  